src/Entity/Cart.php
<?php

namespace App\Entity;

use App\Repository\CartRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CartRepository::class)]
class Cart
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'carts')]
    private ?User $user = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $cart_status = null;

    #[ORM\Column(nullable: true)]
    private ?int $total_items = null;

    #[ORM\Column(nullable: true)]
    private ?float $total_price = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $creation_date = null;

    #[ORM\OneToMany(mappedBy: 'cart', targetEntity: CartItem::class)]
    private Collection $cartItems;

    public function __construct()
    {
        $this->cartItems = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->getCartStatus();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getCartStatus(): ?string
    {
        return $this->cart_status;
    }

    public function setCartStatus(?string $cart_status): static
    {
        $this->cart_status = $cart_status;

        return $this;
    }

    public function getTotalItems(): ?int
    {
        return $this->total_items;
    }

    public function setTotalItems(?int $total_items): static
    {
        $this->total_items = $total_items;

        return $this;
    }

    public function getTotalPrice(): ?float
    {
        return $this->total_price;
    }

    public function setTotalPrice(?float $total_price): static
    {
        $this->total_price = $total_price;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(?\DateTimeInterface $creation_date): static
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    /**
     * @return Collection<int, CartItem>
     */
    public function getCartItems(): Collection
    {
        return $this->cartItems;
    }

    public function addCartItem(CartItem $cartItem): static
    {
        if (!$this->cartItems->contains($cartItem)) {
            $this->cartItems->add($cartItem);
            $cartItem->setCart($this);
        }

        return $this;
    }

    public function removeCartItem(CartItem $cartItem): static
    {
        if ($this->cartItems->removeElement($cartItem)) {
            // set the owning side to null (unless already changed)
            if ($cartItem->getCart() === $this) {
                $cartItem->setCart(null);
            }
        }

        return $this;
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $product_name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    private ?float $price = null;

    #[ORM\Column(nullable: true)]
    private ?float $discount_price = null;

    #[ORM\Column(nullable: true)]
    private ?float $stock_quantity = null;

    #[ORM\Column(length: 500, nullable: true)]
    private ?string $images = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $rating = null;

    #[ORM\Column(nullable: true)]
    private ?int $number_of_ratings = null;

    #[ORM\Column(nullable: true)]
    private ?bool $availability = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $features = null;

    #[ORM\Column(nullable: true)]
    private ?float $weight = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_featured = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_new = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_bestseller = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_onsale = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_added = null;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: OrderItem::class)]
    private Collection $orderItems;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: ProductReview::class)]
    private Collection $productReviews;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: CartItem::class)]
    private Collection $cartItems;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: ProductDisplay::class)]
    private Collection $productDisplays;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: ProductImage::class)]
    private Collection $productImages;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $box_size = null;

    #[ORM\ManyToMany(targetEntity: Category::class, inversedBy: 'products')]
    private Collection $categories;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $video_link = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $brand = null;

    public function __construct()
    {
        $this->orderItems = new ArrayCollection();
        $this->productReviews = new ArrayCollection();
        $this->cartItems = new ArrayCollection();
        $this->productDisplays = new ArrayCollection();
        $this->productImages = new ArrayCollection();
        $this->categories = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->getProductName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProductName(): ?string
    {
        return $this->product_name;
    }

    public function setProductName(?string $product_name): static
    {
        $this->product_name = $product_name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(?float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getDiscountPrice(): ?float
    {
        return $this->discount_price;
    }

    public function setDiscountPrice(?float $discount_price): static
    {
        $this->discount_price = $discount_price;

        return $this;
    }

    public function getStockQuantity(): ?float
    {
        return $this->stock_quantity;
    }

    public function setStockQuantity(?float $stock_quantity): static
    {
        $this->stock_quantity = $stock_quantity;

        return $this;
    }

    public function getImages(): ?string
    {
        return $this->images;
    }

    public function setImages(?string $images): static
    {
        $this->images = $images;

        return $this;
    }

    public function getRating(): ?string
    {
        return $this->rating;
    }

    public function setRating(?string $rating): static
    {
        $this->rating = $rating;

        return $this;
    }

    public function getNumberOfRatings(): ?int
    {
        return $this->number_of_ratings;
    }

    public function setNumberOfRatings(?int $number_of_ratings): static
    {
        $this->number_of_ratings = $number_of_ratings;

        return $this;
    }

    public function isAvailability(): ?bool
    {
        return $this->availability;
    }

    public function setAvailability(?bool $availability): static
    {
        $this->availability = $availability;

        return $this;
    }

    public function getFeatures(): ?string
    {
        return $this->features;
    }

    public function setFeatures(?string $features): static
    {
        $this->features = $features;

        return $this;
    }

    public function getWeight(): ?float
    {
        return $this->weight;
    }

    public function setWeight(?float $weight): static
    {
        $this->weight = $weight;

        return $this;
    }

    public function isIsFeatured(): ?bool
    {
        return $this->is_featured;
    }

    public function setIsFeatured(?bool $is_featured): static
    {
        $this->is_featured = $is_featured;

        return $this;
    }

    public function isIsNew(): ?bool
    {
        return $this->is_new;
    }

    public function setIsNew(?bool $is_new): static
    {
        $this->is_new = $is_new;

        return $this;
    }

    public function isIsBestseller(): ?bool
    {
        return $this->is_bestseller;
    }

    public function setIsBestseller(?bool $is_bestseller): static
    {
        $this->is_bestseller = $is_bestseller;

        return $this;
    }

    public function isIsOnsale(): ?bool
    {
        return $this->is_onsale;
    }

    public function setIsOnsale(?bool $is_onsale): static
    {
        $this->is_onsale = $is_onsale;

        return $this;
    }

    public function getDateAdded(): ?\DateTimeInterface
    {
        return $this->date_added;
    }

    public function setDateAdded(?\DateTimeInterface $date_added): static
    {
        $this->date_added = $date_added;

        return $this;
    }

    /**
     * @return Collection<int, OrderItem>
     */
    public function getOrderItems(): Collection
    {
        return $this->orderItems;
    }

    public function addOrderItem(OrderItem $orderItem): static
    {
        if (!$this->orderItems->contains($orderItem)) {
            $this->orderItems->add($orderItem);
            $orderItem->setProduct($this);
        }

        return $this;
    }

    public function removeOrderItem(OrderItem $orderItem): static
    {
        if ($this->orderItems->removeElement($orderItem)) {
            // set the owning side to null (unless already changed)
            if ($orderItem->getProduct() === $this) {
                $orderItem->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ProductReview>
     */
    public function getProductReviews(): Collection
    {
        return $this->productReviews;
    }

    public function addProductReview(ProductReview $productReview): static
    {
        if (!$this->productReviews->contains($productReview)) {
            $this->productReviews->add($productReview);
            $productReview->setProduct($this);
        }

        return $this;
    }

    public function removeProductReview(ProductReview $productReview): static
    {
        if ($this->productReviews->removeElement($productReview)) {
            // set the owning side to null (unless already changed)
            if ($productReview->getProduct() === $this) {
                $productReview->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, CartItem>
     */
    public function getCartItems(): Collection
    {
        return $this->cartItems;
    }

    public function addCartItem(CartItem $cartItem): static
    {
        if (!$this->cartItems->contains($cartItem)) {
            $this->cartItems->add($cartItem);
            $cartItem->setProduct($this);
        }

        return $this;
    }

    public function removeCartItem(CartItem $cartItem): static
    {
        if ($this->cartItems->removeElement($cartItem)) {
            // set the owning side to null (unless already changed)
            if ($cartItem->getProduct() === $this) {
                $cartItem->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ProductDisplay>
     */
    public function getProductDisplays(): Collection
    {
        return $this->productDisplays;
    }

    public function addProductDisplay(ProductDisplay $productDisplay): static
    {
        if (!$this->productDisplays->contains($productDisplay)) {
            $this->productDisplays->add($productDisplay);
            $productDisplay->setProduct($this);
        }

        return $this;
    }

    public function removeProductDisplay(ProductDisplay $productDisplay): static
    {
        if ($this->productDisplays->removeElement($productDisplay)) {
            // set the owning side to null (unless already changed)

src/Form/CartType.php
<?php

namespace App\Form;

use App\Entity\Orderr;
use App\Form\EventListener\ClearCartListener;
use App\Form\EventListener\RemoveCartItemListener;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CartType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('orderItems', CollectionType::class, [
                'entry_type' => CartItemType::class
            ])
            ->add('save', SubmitType::class)
            ->add('clear', SubmitType::class);

        $builder->addEventSubscriber(new RemoveCartItemListener());
        $builder->addEventSubscriber(new ClearCartListener());
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Orderr::class,
        ]);
    }
}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %} 

    {{ leogout_seo() }} 
    <style>

/* Add this CSS to your stylesheet */
.cart-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;
  max-width:700px;
}

.list-unstyled {
  width: 100%; /* Set the width of the list to 100% */
  padding: 0;
  list-style: none;
}

.cart-item {
  width: 100%; /* Set the width of each cart item to 100% */
  margin-bottom: 20px;
  padding: 15px;
  border: 1px solid #ddd;
  border-radius: 5px;
  font-family: 'Arial', sans-serif;
}

.cart-link {
  color: #333;
  text-decoration: none;
  font-weight: bold;
}

.cart-price,
.cart-total {
  color: #555;
}

.invalid-feedback {
  color: #d9534f;
}

/* Optional: Style for hover effect */
.cart-item:hover {
  background-color: #f9f9f9;
}



    </style>

{% endblock %}

{% block page %}

      <section class="breadcrumbs-custom">
        <div class="parallax-container" data-parallax-img="/site/images/njiani-backdrop-banner.jpg">
          <div class="breadcrumbs-custom-body parallax-content">
            <div class="container">
              <h1 class="breadcrumbs-custom-title">Your Cart</h1>
            </div>
          </div>
        </div>
        <div class="breadcrumbs-custom-footer">
          <div class="container">
            <ul class="breadcrumbs-custom-path">
              <li><a href="{{path('app_default')}}">Home</a></li>
              <li><a href="#">Shop</a></li>
              <li class="active">Your Cart</li>
            </ul>
          </div>
        </div>
      </section>

    {% if cart.orderItems.count > 0 %}

    {{ form_start(form) }}
        <!-- Shopping Cart-->
        <section class="section section-xl bg-default" style="padding-top:0;">
            <div class="container">
                <!-- shopping-cart-->
                <div class="table-custom-responsive" style="margin-top:0;">
                    <section class="section section-sm bg-default text-md-left">
                    <div class="container cart-container">
                        <h3 class="font-weight-medium" style="font-size:1.4em">Your shopping cart</h3>
                        <ul class="list-unstyled">
                        {% for item in form.orderItems %}
                            <li class="cart-item">
                            <a href="{{ path('product_show', {'product_slug': item.vars.data.product.slug }) }}" class="cart-figure">
                                <img src="/site/images/products/{{ item.vars.data.product.images }}" alt="" width="58" height="132"/>
                            </a>
                            <div class="cart-details">
                                <a href="{{ path('product_show', {'product_slug': item.vars.data.product.slug }) }}" class="cart-link">{{ item.vars.data.product.productName }}</a>
                                <div class="cart-price">KSh {{ item.vars.data.product.price }}</div>
                                <div class="cart-quantity">
                                <div class="table-cart-stepper">
                                    {{ form_widget(item.quantity, {
                                    'attr': {
                                        'class': 'form-input form-control-sm ' ~ (item.quantity.vars.valid ? '' : 'is-invalid'),
                                        'data-zeros': 'true',
                                        'value': item.quantity.vars.value,
                                        'min': '1',
                                        'max': '1000'
                                    }
                                    }) }}
                                    <div class="invalid-feedback">
                                    {{ form_errors(item.quantity) }}
                                    </div>
                                </div>
                                </div>
                                <div class="cart-total">Total: KSh {{ item.subTotal.vars.value }}</div>
                                <div class="cart-action">{{ form_widget(item.remove, {'attr': {'class': 'btn btn-dark btn-sm'}}) }}</div>
                            </div>
                            </li>
                        {% endfor %}
                        </ul>
                    </div>
                    </section>
                </div>
                <div class="group-xl group-justify justify-content-center justify-content-md-between">
                    <div>
                        <div class="form-button">
                        {{ form_widget(form.save, {'attr': {'class': 'button button-lg button-default-outline-2 button-zakaria'}}) }}
                        {{ form_widget(form.clear, {'attr': {'class': 'button button-lg ', 'style': 'margin-top:0'}}) }}
                        </div>
                    </div>
                    <div>
                    <div class="group-xl group-middle">
                        <div>
                        <div class="group-md group-middle">
                            <div class="heading-5 font-weight-medium text-gray-500">Total</div>
                            <div class="heading-3 font-weight-normal">KSh {{ cart.total }}</div>
                        </div>
                        </div><a class="button button-lg button-primary button-zakaria" href="{{ path('checkout') }}">Proceed to checkout</a>
                    </div>
                    </div>
                </div>
            </div>
        </section>
        {{ form_row(form._token) }}
    {{ form_end(form, {'render_rest': false}) }}
    {% else %}
        <div class="alert alert-info">
            Your cart is empty. Go to the <a href="{{ path('app_default') }}">Home page</a>.
        </div>
    {% endif %}



{% endblock %}

templates/cart/order_received.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %} 
    {{ leogout_seo() }} 
    <style>

/* Add this CSS to your stylesheet */
.cart-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;
  max-width:700px;
}

.list-unstyled {
  width: 100%; /* Set the width of the list to 100% */
  padding: 0;
  list-style: none;
}

.cart-item {
  width: 100%; /* Set the width of each cart item to 100% */
  margin-bottom: 20px;
  padding: 15px;
  border: 1px solid #ddd;
  border-radius: 5px;
  font-family: 'Arial', sans-serif;
}

.cart-link {
  color: #333;
  text-decoration: none;
  font-weight: bold;
}

.cart-price,
.cart-total {
  color: #555;
}

.invalid-feedback {
  color: #d9534f;
}

/* Optional: Style for hover effect */
.cart-item:hover {
  background-color: #f9f9f9;
}


        /* Add some basic styling */
        #container {
            position: relative;
        }

        #searchInput {
            width: 100%;
            box-sizing: border-box;
            padding: 5px;
            margin-bottom: 5px;
        }

        #routeSelect {
            width: 100%;
        }

    </style>

{% endblock %}
{% block page %}

      <section class="breadcrumbs-custom">
        <div class="parallax-container" data-parallax-img="/site/images/njiani-backdrop-banner.jpg">
          <div class="breadcrumbs-custom-body parallax-content">
            <div class="container">
              <h2 class="breadcrumbs-custom-title">Order Confirmation</h2>
            </div>
          </div>
        </div>
        <div class="breadcrumbs-custom-footer">
          <div class="container">
            <ul class="breadcrumbs-custom-path">
              <li><a href="{{ path('app_default')}}">Home</a></li>
              <li><a href="#">Shop</a></li>
              <li class="active">Order Confirmation</li>
            </ul>
          </div>
        </div>
      </section>
      <!-- Section checkout form-->
      <section class="section section-sm section-first bg-default text-md-left">
        <div class="container">
          <div class="row row-50 justify-content-center">
            <div class="col-md-10 col-lg-6">
                <div class="table-custom-responsive" style="margin-top:0;">
                    <div class="container cart-container">
                        <h3 class="font-weight-medium">Your shopping</h3>
                        <ul class="list-unstyled">
                        {% for item in cart.orderItems %}
                            <li class="cart-item">
                            <a href="{{ path('product_show', {'product_slug': item.product.slug}) }}" class="cart-figure">
                                <img src="/site/images/products/{{ item.product.images }}" alt="" width="58" height="132"/>
                            </a>
                            <div class="cart-details">
                                <a href="{{ path('product_show', {'product_slug': item.product.slug}) }}" class="cart-link">{{ item.product.productName }}</a>
                                <div class="cart-price">Each: KSh {{ item.product.price }}</div>
                                <div class="cart-quantity">
                                <div class="table-cart-stepper">
                                    Quantity: {{item.quantity}}
                                </div>
                                </div>
                                <div class="cart-total">Total: KSh {{ item.subTotal }}</div>
                            </div>
                            </li>
                        {% endfor %}
                        </ul>
                    </div>
                </div>
            


            </div>
            <div class="col-md-10 col-lg-6">
              <div class="table-custom-responsive">
                <div class="container cart-container">

                <h3 class="font-weight-medium">Shopping total</h3>
                <table class="table-custom table-custom-primary table-checkout">
                  <tbody>
                    <tr>
                      <td>Shopping Subtotal</td>
                      <td>KSh {{cart.total}}<br/>(Tax inclusive)</td>
                    </tr>
                    <tr>
                      <td>Shipping</td>
                      <td><span id="shipping_cost">{{shipping}}</span></td>
                    </tr>
                    <tr>
                      <td>Total</td>
                      <td>KSh {{ cart.total + shipping}}</td>
                    </tr>
                  </tbody>
                </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <!-- Shopping Cart-->




{% endblock %}

templates/cart/payment_page.html.twig
{{dump(test)}}